#
name: Extract and Clear

on: [push]

jobs:
  run_dataExtract:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements (Extract)
        run: |
          python -m pip install --upgrade pip
          pip install -r Extract/Passing/requirements_extract_passing.txt

      - name: Executa Notebook
        run: |
          jupyter execute Extract/Passing/Passing_Extract.ipynb
        shell: bash 
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          add: 'AED'
          message: 'AED'

  run_dataClear:
    needs: run_dataExtract
    runs-on: ubuntu-latest

    steps:
      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements (Cleaning)
        run: |
          python -m pip install --upgrade pip
          pip install -r Cleaning/Passing/requirementx_cleaning_passing.txt

      - name: Executa Notebook
        run: |
          jupyter execute Cleaning/Passing/Passing_Union_Clear.ipynb
        shell: bash 
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          add: 'AED'
          message: 'AED'